config/routes.rb

Fixes issue with logged in users not seeing @adamjarling's `/aboutnu` page in #62

have the nu routes resolve before the general about route

---

app/assets/stylesheets/nu_avalon/components/_accordion.scss

Fixes #169 Sections list remove bullet styles, fix padding, and updating arrow color to NU purple

Sections area cleanup

---

app/assets/stylesheets/nu_avalon/main.scss
app/assets/stylesheets/nu_avalon/pages/_my-collections.scss
app/assets/stylesheets/nu_avalon/pages/_search-results.scss
app/views/admin/collections/_form.html.erb
app/views/admin/collections/index.html.erb

General cleanup of UI with collections list and adding a new collection.

Collections list updates #171

---

app/models/concerns/master_file_behavior.rb

use html_safe for embed title due to quotes in title

---

Gemfile
Gemfile.lock

Move over Adam's fix for a loading screen

Deploy aws staging

---

app/assets/javascripts/nu-avalon/script.js

There was a bug in the loader polling code.  This should do it.

Loader spinner bug fix

---

app/assets/javascripts/nu-avalon/script.js
app/assets/stylesheets/nu_avalon/components/_loader.scss
app/assets/stylesheets/nu_avalon/layout/_nav.scss
app/assets/stylesheets/nu_avalon/main.scss
app/assets/stylesheets/nuwebcomm/_nuwebcomm_overrides.scss

Reverts nulib/avalon#197
deploy failed, reverting this code out of production

Revert "Deploy aws staging"

---

app/assets/javascripts/nu-avalon/script.js
app/assets/stylesheets/nu_avalon/components/_loader.scss
app/assets/stylesheets/nu_avalon/layout/_nav.scss
app/assets/stylesheets/nu_avalon/main.scss
app/assets/stylesheets/nuwebcomm/_nuwebcomm_overrides.scss

Revert "Update loader script to be namespaced, and fix centering of loader"

---

Gemfile
Gemfile.lock
app/views/layouts/avalon.html.erb
config/environments/production.rb

enabled basic Google Analytics for avalon

---

app/controllers/master_files_controller.rb
app/controllers/media_objects_controller.rb
app/helpers/security_helper.rb

Fixes #230 
The cherry-pick went sour due to history getting merged and rather than deal with the bad revision problems in GitHub, I just went ahead and redid all three lines of work.

set cookies, fixes work lost during a merge

---

.gitignore
app/assets/stylesheets/nu_avalon/base/_typography.scss
app/assets/stylesheets/nu_avalon/components/_accordion.scss
app/assets/stylesheets/nu_avalon/components/_mediaelement.scss
app/assets/stylesheets/nu_avalon/components/_pagination.scss
app/assets/stylesheets/nu_avalon/components/_web-upload.scss
app/assets/stylesheets/nu_avalon/layout/_forms.scss
app/controllers/playlists_controller.rb
app/views/nu_playlists/item_list.html.erb

Fixes in place for #244 #250 #266 #270 #271

UI fixes for #244 #250 #266 #270 #271

---

app/views/nu_catalog/_home_text.html.erb

Fixes #257  - Just to check if I can develop on this repo while you guys are busy next week.

Update homepage relative url paths

---

app/jobs/batch_ingest_job.rb
lib/avalon/batch/ingest.rb

Cherry-picked from public.
@mbklein is the lambda already up or so we need to bring it back?

Bring over new batch for S3

---

config/application.rb

actually use the right redis config

---

app/jobs/active_encode_job.rb
app/jobs/ingest_batch_entry_job.rb

add explicit falses just for clarity and throttle the updates further

---

app/jobs/active_encode_job.rb
app/jobs/ingest_batch_entry_job.rb

slow down further on the initial ingest side

---

app/jobs/active_encode_job.rb
app/jobs/ingest_batch_entry_job.rb

#refs 313
use environment variables

use config variables

---

app/models/elastic_transcoder_job.rb

reduce encode qualities, remove aac audio and rtmp video

---

app/views/playlist_items/_item_list.html.erb

Fixes #334 
bring back local styling

restore item list

---

app/mailers/batch_registries_mailer.rb

order the mailer so it ascends

---

app/views/playlists/show.html.erb

fix partial calls

---

spec/controllers/master_files_controller_spec.rb
spec/models/master_file_spec.rb

Don't force-load all sections just to get a count

---

app/assets/javascripts/media_player_wrapper/avalon_player_new.es6
app/assets/javascripts/media_player_wrapper/mejs4_plugin_add_to_playlist.es6
app/assets/javascripts/media_player_wrapper/mejs4_plugin_playlist_items.es6
app/assets/stylesheets/avalon.scss
app/helpers/media_objects_helper.rb

This is a cherry pick of avalonmediasystem/avalon#2780 to support our near-term deployment

Playlist indicator fix
